# Generated by Django 2.2.2 on 2019-06-26 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='orginfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orgs.OrgInfo', verbose_name='所属机构'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='teacherinfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orgs.TeacherInfo', verbose_name='所属讲师'),
            preserve_default=False,
        ),
    ]
