# Generated by Django 2.2.2 on 2019-08-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_auto_20190805_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginfo',
            name='detail',
            field=models.TextField(verbose_name='机构详情'),
        ),
    ]
